using UnityEngine;
using System.Collections.Generic;
using FluffyUnderware.Curvy;
using RootMotion.FinalIK;
using RootMotion.Dynamics;

public class Girl : MonoBehaviour
{
	public List<AdvancedCollider> m_colliders;
	public List<SoxAtkJiggleBoneSimple> m_jiggleBones;
	public List<GirlToggle> m_toggles;
	public Rig m_rig;
	public FaceRig m_face;
	public RuntimeAnimatorController m_controller;
	public Animation m_anim;
	public Animator m_animator;
	public AnimatorOverrideController m_overrideController;
	public List<CurvySplineSegment> m_mouth;
	public FullBodyBipedIK m_bipedIK;
	public IK m_headIK;
	public IK m_lEyeIK;
	public IK m_rEyeIK;
	public IK m_lHandIK;
	public IK m_rHandIK;
	public IK m_hipsIK;
	public IK m_lFootIK;
	public IK m_rFootIK;
	public Transform m_lThighIK;
	public Transform m_rThighIK;
	public FBBIKHeadEffector m_headEffector;
	public float m_hipsWeight;
	public PuppetMaster m_puppet;
	public Penis m_penis;
	public Rig m_puppetRig;
	public List<RenderMaterial> m_renderMaterials;
	public FluidSmear mascaraSmear;
	public float m_openMouthWeight;
	public float m_eyeDownWeight;
	public Vector2 m_mouthLimit;
	public Vector2 m_mouthLimitFade;
	public float m_speakFrequency;
	public float m_juiceAmount;
	public float m_hipsSpeed;
	public bool m_updateAnim;
	public AudioClip m_music;
	public float m_musicVolume;
	public float m_voiceVolume;
	public List<AudioClip> m_voiceLines;
	public List<OVRLipSyncSequence> m_lipsyncs;
	public float m_throatDistance;
	public float m_cheekDistance;
	public float m_mouthLerpSpeed;
	public float m_maxMouthSize;
	public float m_penisRotSpd;
	public float m_penisAimSpd;
	public float m_autoSpeed;
	public float m_autoDepth;
	public float m_autoTime;
	public bool m_autoInPhase;
	public bool m_headLock;
	public bool m_hipsLock;
	public SkinnedMeshRenderer m_convertRenderer;
	public bool m_convertSkin;
	public float m_mouthSqueezeDist;
	public float m_mouthSqueeze;
	public float m_mouthSlide;
	public Vector2 m_hackHeadLimit;
}
